pub mod aggregate;
pub mod asset_init;
pub mod asset_manager;
pub mod bundle;
pub mod character;
pub mod download;
pub mod item;
pub mod multiplayer;
pub mod notification;
pub mod operations;
pub mod present;
pub mod purchase;
pub mod score;
pub mod user;
pub mod world;

// Re-export commonly used service types for convenience
pub use asset_init::AssetInitService;
pub use asset_manager::AssetManager;
pub use bundle::BundleService;
pub use character::CharacterService;
pub use download::DownloadService;
pub use item::{ItemFactory, ItemService, UserItemList};
pub use multiplayer::{MatchmakingJoinRequest, MultiplayerService, MultiplayerUpdateRequest};
pub use notification::NotificationService;
pub use operations::OperationManager;
pub use present::PresentService;
pub use purchase::PurchaseService;
pub use score::ScoreService;
pub use user::UserService;
pub use world::WorldService;
